USE air_flights_db
GO

SET TRANSACTION ISOLATION LEVEL SNAPSHOT

BEGIN TRY
	BEGIN TRANSACTION
		INSERT INTO cities
			(title)
			VALUES
			('Иркутск')
		INSERT INTO cities
			(title)
			VALUES
			('Архангельск')
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	SELECT ERROR_MESSAGE() AS [Error message]
	RETURN
END CATCH
COMMIT TRANSACTION

GO